### ISSUE TITLE
pinDescription content sometimes disappears

### ISSUE THREAD

**Issue by heyuan110** [pinterest/ios-pdk#40] opened 2015-12-08 08:52 UTC
i called the method

```
+ (void)pinWithImageURL:(NSURL *)imageURL
                   link:(NSURL *)sourceURL
     suggestedBoardName:(NSString *)suggestedBoardName
                   note:(NSString *)pinDescription
            withSuccess:(PDKUnauthPinCreationSuccess)pinSuccessBlock
             andFailure:(PDKUnauthPinCreationFailure)pinFailureBlock

```

worked fine ,but the pinDescription content sometimes disappears, is there any limit on pinDescription? such as pinDescription length limit?

**Comment by connor** [comment] 2016-02-15 22:29
I can't reproduce this, @heyuan110 – are you still having issues? Do you happen to have the exact description that has been erroring?

**Comment by connor** [comment] 2016-02-25 15:07
Closing out to clean up the issues list; if the issue still persists and you can provide steps to reproduce, please re open!

**Closed by connor** 2016-02-25 15:07 UTC
